name: proxy
on: workflow_dispatch
jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
     - name: start
       env:
          CPOLAR_AUTHTOKEN: ${{ secrets.CPOLAR_AUTHTOKEN }}
       run: |
          sudo apt --force-yes -y install tinyproxy 
          sudo service tinyproxy restart
          sudo curl -L https://www.cpolar.com/static/downloads/install-release-cpolar.sh | sudo bash
          echo '' > /usr/local/etc/cpolar/cpolar.yml
          cpolar authtoken $CPOLAR_AUTHTOKEN
          sudo systemctl start cpolar
          cpolar tcp -region=us 8888 &
          echo 'go to https://dashboard.cpolar.com/status check your proxy address.'
