name: proxy

on: workflow_dispatch


jobs:
  vpn:
    runs-on: ubuntu-latest
    steps:
     - name: checkout actions
       uses: actions/checkout@v1
     - name: start
       run:
         bash cpolar_run.sh
